In [31]:
from numpy import *

num_movies = 10 # define the number of movies in our 'database'

num_users = 5 # define the number of users in our 'database'

# randomly initialize some movie ratings 
ratings = random.randint(11, size = (num_movies, num_users))

print(ratings)

[[ 1  4  1  7  4]
 [ 3  4  8  2 10]
 [ 4  1 10  2  4]
 [ 1  9  7  4  8]
 [ 0  8  0  5  4]
 [10  5  5  1  4]
 [ 3 10 10  3  3]
 [10  5  3  9  9]
 [ 5  7  0  1  3]
 [ 9  8 10  7  5]]


In [32]:
# create a logical matrix (matrix that represents whether a rating was made, or not)

did_rate = (ratings != 0) * 1

print(did_rate)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]]


In [33]:
# Let's make some ratings. A 10 X 1 column vector to store all the ratings I make

vishnu_ratings = zeros((num_movies, 1))
print(vishnu_ratings)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [34]:
# I rate 3 movies

vishnu_ratings[0] = 8
vishnu_ratings[4] = 7
vishnu_ratings[7] = 3

print(vishnu_ratings)

[[ 8.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 7.]
 [ 0.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 0.]]


In [35]:
# Update ratings and did_rate
ratings = append(vishnu_ratings, ratings, axis = 1)
did_rate = append(((vishnu_ratings != 0) * 1), did_rate, axis = 1)

print(ratings)
print(did_rate)
did_rate.shape

[[  8.   1.   4.   1.   7.   4.]
 [  0.   3.   4.   8.   2.  10.]
 [  0.   4.   1.  10.   2.   4.]
 [  0.   1.   9.   7.   4.   8.]
 [  7.   0.   8.   0.   5.   4.]
 [  0.  10.   5.   5.   1.   4.]
 [  0.   3.  10.  10.   3.   3.]
 [  3.  10.   5.   3.   9.   9.]
 [  0.   5.   7.   0.   1.   3.]
 [  0.   9.   8.  10.   7.   5.]]
[[1 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [1 0 1 0 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [1 1 1 1 1 1]
 [0 1 1 0 1 1]
 [0 1 1 1 1 1]]


(10, 6)

In [36]:
# a function that normalizes a dataset

def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape = (num_movies, 1))
    ratings_norm = zeros(shape = ratings.shape)
    
    for i in range(num_movies): 
        # Get all the indexes where there is a 1
        idx = where(did_rate[i] == 1)[0]
        #  Calculate mean rating of ith movie only from user's that gave a rating
        ratings_mean[i] = mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
    
    return ratings_norm, ratings_mean

In [37]:
# Normalize ratings

ratings, ratings_mean = normalize_ratings(ratings, did_rate)


print(ratings)

# Update some key variables now

num_users = ratings.shape[1]
num_features = 3 # Comedy, Action, Romance

[[ 3.83333333 -3.16666667 -0.16666667 -3.16666667  2.83333333 -0.16666667]
 [ 0.         -2.4        -1.4         2.6        -3.4         4.6       ]
 [ 0.         -0.2        -3.2         5.8        -2.2        -0.2       ]
 [ 0.         -4.8         3.2         1.2        -1.8         2.2       ]
 [ 1.          0.          2.          0.         -1.         -2.        ]
 [ 0.          5.          0.          0.         -4.         -1.        ]
 [ 0.         -2.8         4.2         4.2        -2.8        -2.8       ]
 [-3.5         3.5        -1.5        -3.5         2.5         2.5       ]
 [ 0.          1.          3.          0.         -3.         -1.        ]
 [ 0.          1.2         0.2         2.2        -0.8        -2.8       ]]


In [38]:
# Initialize Parameters theta (user_prefs), X (movie_features)

movie_features = random.randn( num_movies, num_features )
user_prefs = random.randn( num_users, num_features )
initial_X_and_theta = r_[movie_features.T.flatten(), user_prefs.T.flatten()]

print(movie_features)

[[ 0.28729002  0.83667862  0.17763265]
 [ 0.44994029  0.75871716  0.60415934]
 [-1.33414121  1.12077651  0.51294879]
 [-0.54811157 -3.0264879   1.08458274]
 [-1.06313731 -0.72988133  0.2641025 ]
 [-2.0055737  -0.28799122 -0.09253125]
 [ 0.38883319  0.39072266 -0.60346166]
 [-0.45470159 -1.17661138 -0.14017454]
 [-0.98107516  2.16633688 -1.75716689]
 [-0.39259843 -0.58755351  0.60345537]]


In [39]:
print(user_prefs)

[[ 0.40128147 -1.04294776  1.42338513]
 [ 0.49340708 -0.70905719 -2.31782483]
 [ 0.0108862   0.2333861  -0.5271819 ]
 [ 1.16208991  0.99890847  0.31135202]
 [ 1.07586828 -0.54385544 -0.18148047]
 [ 1.38729253  1.62229062 -0.19827528]]


In [40]:
print(initial_X_and_theta)

[ 0.28729002  0.44994029 -1.33414121 -0.54811157 -1.06313731 -2.0055737
  0.38883319 -0.45470159 -0.98107516 -0.39259843  0.83667862  0.75871716
  1.12077651 -3.0264879  -0.72988133 -0.28799122  0.39072266 -1.17661138
  2.16633688 -0.58755351  0.17763265  0.60415934  0.51294879  1.08458274
  0.2641025  -0.09253125 -0.60346166 -0.14017454 -1.75716689  0.60345537
  0.40128147  0.49340708  0.0108862   1.16208991  1.07586828  1.38729253
 -1.04294776 -0.70905719  0.2333861   0.99890847 -0.54385544  1.62229062
  1.42338513 -2.31782483 -0.5271819   0.31135202 -0.18148047 -0.19827528]


In [41]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
	# Retrieve the X and theta matrixes from X_and_theta, based on their dimensions (num_features, num_movies, num_movies)
	# --------------------------------------------------------------------------------------------------------------
	# Get the first 30 (10 * 3) rows in the 48 X 1 column vector
	first_30 = X_and_theta[:num_movies * num_features]
	# Reshape this column vector into a 10 X 3 matrix
	X = first_30.reshape((num_features, num_movies)).transpose()
	# Get the rest of the 18 the numbers, after the first 30
	last_18 = X_and_theta[num_movies * num_features:]
	# Reshape this column vector into a 6 X 3 matrix
	theta = last_18.reshape(num_features, num_users ).transpose()
	return X, theta

In [42]:
def calculate_gradient(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	# we multiply by did_rate because we only want to consider observations for which a rating was given
	difference = X.dot( theta.T ) * did_rate - ratings
	X_grad = difference.dot( theta ) + reg_param * X
	theta_grad = difference.T.dot( X ) + reg_param * theta
	
	# wrap the gradients back into a column vector 
	return r_[X_grad.T.flatten(), theta_grad.T.flatten()]

In [43]:
def calculate_cost(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	# we multiply (element-wise) by did_rate because we only want to consider observations for which a rating was given
	cost = sum( (X.dot( theta.T ) * did_rate - ratings) ** 2 ) / 2
	# '**' means an element-wise power
	regularization = (reg_param / 2) * (sum( theta**2 ) + sum(X**2))
	return cost + regularization

In [44]:
# Lets Make Some Predictions :D
from scipy import optimize
reg_param = 30

minimized_cost_and_optimal_params = optimize.fmin_cg(
                calculate_cost,
                fprime=calculate_gradient,
                x0=initial_X_and_theta,
                args=(
                    ratings,
                    did_rate,
                    num_users,
                    num_movies,
                    num_features,
                    reg_param),
                maxiter=100,
                disp=True,
                full_output=True )

Optimization terminated successfully.
         Current function value: 189.366667
         Iterations: 11
         Function evaluations: 23
         Gradient evaluations: 23


In [45]:
cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]

movie_features, user_prefs = unroll_params(optimal_movie_features_and_user_prefs, num_users, num_movies, num_features)

print(movie_features)

[[  8.15802500e-08  -4.62497096e-08   1.59294756e-07]
 [ -1.92461167e-07   3.11473450e-09  -1.59896010e-07]
 [ -1.86551894e-07  -1.29592127e-07  -1.31146745e-07]
 [ -4.18890158e-08   2.07719667e-08  -3.36649972e-08]
 [  4.01310913e-08   6.45647481e-08   1.08893540e-07]
 [ -9.67461597e-08   1.03913889e-07  -9.93492082e-09]
 [  9.70711297e-08   7.62352250e-08  -3.98628676e-08]
 [ -1.29668675e-07   3.12506675e-08  -9.37551596e-08]
 [ -1.11414710e-07   2.20967001e-07  -1.44213851e-07]
 [  1.01829767e-07  -3.39828760e-08   1.19425163e-07]]


In [46]:
print(user_prefs)

[[  3.89664692e-08   9.24322433e-08   1.77847081e-07]
 [  1.59444914e-08  -4.21368536e-08  -1.25861272e-07]
 [  1.90906708e-07  -1.98363958e-07   2.14967772e-07]
 [  3.48676970e-08   1.60881517e-08  -8.04594470e-08]
 [  8.88489146e-08   9.34337955e-08  -1.01377153e-08]
 [  1.31873690e-08  -2.63041447e-07  -2.00985195e-07]]


In [47]:
# Make some predictions (movie recommendations). Dot product

all_predictions = movie_features.dot( user_prefs.T )

print(all_predictions)

[[  2.72340372e-14  -1.67994678e-14   5.89917311e-14  -1.07163249e-14
    1.31214589e-15  -1.87744682e-14]
 [ -3.56486689e-14   1.69247747e-14  -7.17324678e-14   6.20457723e-15
   -1.51879641e-14   2.87793701e-14]
 [ -4.25718254e-14   1.89924255e-14  -3.80999242e-14   1.96246188e-15
   -2.73536892e-14   5.79865260e-14]
 [ -5.69948905e-15   2.69395500e-15  -1.93541931e-14   1.58227610e-15
   -1.43970374e-15   7.49871950e-16]
 [  2.68980297e-14  -1.57861650e-14   1.82625773e-14  -6.32350785e-15
    8.49420166e-15  -3.83399707e-14]
 [  4.06824091e-15  -4.67075086e-15  -4.12179488e-14  -9.02175142e-16
    1.21399512e-15  -2.66127149e-14]
 [  3.73961741e-15   3.35262851e-15  -5.16002302e-15   7.81847489e-15
    1.61517293e-14  -1.07610649e-14]
 [ -1.88382426e-14   8.41583775e-15  -5.11079637e-14   3.52500570e-15
   -7.65058945e-15   8.91318956e-15]
 [ -9.56497467e-15   7.06363365e-15  -9.61030346e-14   1.12735430e-14
    1.22087085e-14  -3.06078977e-14]
 [  2.20662497e-14  -1.19754476e-14  

In [48]:
# add back the ratings_mean column vector to my (our) predictions

predictions_for_vishnu = all_predictions[:, 0:1] + ratings_mean

print(predictions_for_vishnu)

[[ 4.16666667]
 [ 5.4       ]
 [ 4.2       ]
 [ 5.8       ]
 [ 6.        ]
 [ 5.        ]
 [ 5.8       ]
 [ 6.5       ]
 [ 4.        ]
 [ 7.8       ]]
